### ISSUE TITLE
Ollama Compatibility

### ISSUE THREAD

**Issue by asbisen** [svilupp/LLMTextAnalysis.jl#18]
It does not seems like this could work with Ollama out of the box. I could get `build_index` to work using the following modification. 

```Julia
PromptingTools.register_model!(name = "nomic-embed-text", schema = PromptingTools.OllamaSchema(), description = "Ollama Nomic Embedding Model")
index = build_index(texts; aiembed_kwargs = (;:model => "nomic-embed-text"))
```

But I can't seem to find a way to pass chat model for `build_clusters!`. Or am I missing something here?

**Comment by asbisen** [comment]
I was able to get things to work, it's a clean mechanism that you have created. For others who get stuck here is what I did. I have Ollama running locally with the said models downloaded. 

```Julia
# to list the model registry
julia> PromptingTools.MODEL_REGISTRY.registry
Dict{String, PromptingTools.ModelSpec} with 32 entries:
  "gemini-pro"                                      => ModelSpec…
  "accounts/fireworks/models/firefunction-v1"       => ModelSpec…
  "gpt-3.5-turbo-1106"                              => ModelSpec…
  "mistral-large-latest"                            => ModelSpec…
  "accounts/fireworks/models/mixtral-8x7b-instruct" => ModelSpec…
  "dall-e-2"                                        => ModelSpec…
  "mistral-embed"                                   => ModelSpec…
  "mistral-medium-latest"                           => ModelSpec…
  "local-server"                                    => ModelSpec…
  "gpt-4-0125-preview"                              => ModelSpec…
  "llava"                                           => ModelSpec…
  "open-mistral-7b"                                 => ModelSpec…
  "gpt-3.5-turbo-0125"                              => ModelSpec…
  "gpt-4-1106-preview"                              => ModelSpec…
  "text-embedding-3-large"                          => ModelSpec…
  "gpt-4-turbo-preview"                             => ModelSpec…
  "text-embedding-3-small"                          => ModelSpec…
  "gpt-4-vision-preview"                            => ModelSpec…
  "mistral-small-latest"                            => ModelSpec…
  "yi:34b-chat"                                     => ModelSpec…
  "open-mixtral-8x7b"                               => ModelSpec…
  "openhermes2.5-mistral"                           => ModelSpec…
  "gpt-3.5-turbo"                                   => ModelSpec…
  "llama2"                                          => ModelSpec…
  "starling-lm"                                     => ModelSpec…
  "bakllava"                                        => ModelSpec…
  "dall-e-3"                                        => ModelSpec…
  "text-embedding-ada-002"                          => ModelSpec…
  "mistralai/Mixtral-8x7B-Instruct-v0.1"            => ModelSpec…
  "gpt-4"                                           => ModelSpec…
  "echo"                                            => ModelSpec…
``` 

Then I added a model to the registry for embedding and specified which model I would like to use for LLM and for CHAT. All this is documented with PromptingTools.jl documentation. 

```Julia
PromptingTools.register_model!(name = "nomic-embed-text", schema = PromptingTools.OllamaSchema(), description = "Ollama Nomic Embedding Model")
PromptingTools.set_preferences!("MODEL_CHAT" => "yi:34b-chat", "MODEL_EMBEDDING" => "nomic-embed-text")
```

After this all functions would use the specified models. No need to individually pass kwargs to function calls.

**Comment by svilupp** [comment]
Thank you sharing! I should add it to FAQ.

I might add nomic and mixedbread embeddings to the official model registry, because they are so common.

**Comment by svilupp** [comment]
One more note, you don't need to set preferences to change which model is being used - it's always driven by the kwargs of the specific function... Eg, for the chat model, you'd change `labeler_kwargs = (;model = "...")` in https://siml.earth/LLMTextAnalysis.jl/dev/api_reference/#LLMTextAnalysis.build_clusters!-Tuple{LLMTextAnalysis.AbstractDocumentIndex}

I need to document it better.

The logic is:
- find the function that does the LLM calls (via looking for "model" argument in the docs)
- pass the `kwargs` set of the right name so it goes to this function

That's how the new RAG interface works as well -> it's not easy to start with, but it makes it fully generic for arbitrary customizations: https://siml.earth/PromptingTools.jl/dev/extra_tools/rag_tools_intro
